# Name of the workflow
name: Basic WebApp Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Install NGINX on the runners
        run: dnf install nginx -y
      # Runs a set of commands using the runners shell
  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Get commit hash
        id: commit
        uses: prompt/actions-commit-hash@v3
      - name: Make sure the web server is running
        run: |
          echo Doing some cool tests
          echo The commit hash is ${{ steps.commit.outputs.short }}
  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Check out Repo
        uses: actions/checkout@v3
      - name: Get commit hash
        id: commit
        uses: prompt/actions-commit-hash@v3
      - name: Deploy app to VM's on Nutanix
        shell: bash
        run: deploy_on_nutanix ${{ steps.commit.outputs.short }}